eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://eureka_registry:8761/eureka} 
  instance:
    hostname: ec2-user
